name: Build realtime AI comfyui docker image

on:
  pull_request:
    paths:
      - "runner/docker/Dockerfile.live-*"
      - "runner/app/**"
      - "runner/images/**"
      - "runner/VERSION"
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - "runner/docker/Dockerfile.live-*"
      - "runner/app/**"
      - "runner/images/**"
      - "runner/VERSION"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ !((github.ref_type == 'branch' && github.ref_name == 'main') || github.ref_type == 'tag') }}

jobs:
  runner:
    name: Build comfyui image
    runs-on: [self-hosted, linux, amd64]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for app image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: livepeer/ai-runner
          tags: |
            type=raw,value=live-app-comfyui,enable={{is_default_branch}}
            type=sha,prefix=live-app-comfyui-sha-
            type=sha,format=long,prefix=live-app-comfyui-sha-
            type=ref,event=pr,prefix=live-app-comfyui-pr-
            type=ref,event=tag,prefix=live-app-comfyui-
            type=ref,event=branch,prefix=live-app-comfyui-
            type=raw,value=latest,enable={{is_default_branch}},prefix=live-app-comfyui-

      - name: Get version information (for docker build tag)
        id: version
        run: |
          echo "version=$(bash runner/print_version.sh)" >> "$GITHUB_OUTPUT"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_TOKEN }}

      - name: Build and push comfyui image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:runner"
          provenance: mode=max
          sbom: true
          push: true
          file: docker/Dockerfile.live-app-comfyui
          build-args: |
            GIT_SHA=${{ (github.ref_type == 'tag' && github.ref_name) || (github.event.pull_request.head.sha || github.sha) }}
            VERSION=${{ steps.version.outputs.version }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=livepeer/ai-runner:live-app-comfyui-dockerbuildcache
          cache-to: type=registry,ref=livepeer/ai-runner:live-app-comfyui-dockerbuildcache,mode=max

      - name: Notify new build upload
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
